## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

##Importing the dataset 

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/LANDSLIDE/Merged_World_LandslideData.csv')
df.size

755706

##Taking care of missing value

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head()

Index  landslide_category  landslide_size  fatality_count  Latitude  \
0   1858                   7               2               0     16.92   
1   1141                   6               2               4     30.38   
4     55                   6               1               0     42.97   
5   4000                   6               2               2     37.75   
6   5609                   7               3               0     47.27   

   Longitude  temp-2  temp-1  temp-0  maxt-2  ...  avgslope  LC_Type1_mean  \
0      73.59    26.3    26.5    26.2    27.7  ...    27.875       9.000000   
1      78.09    26.7    27.2    25.8    28.1  ...    81.375       9.000000   
4    -124.01    11.8     8.3     7.8    14.7  ...    88.875       1.000000   
5     -25.20    14.0    14.1    15.8    17.0  ...   167.000       7.058824   
6    -122.26    11.4    11.3    10.6    14.8  ...    40.000       6.764706   

   LST_Day_1km_mean  NDVI_mean  NDWI_mean     aspect  elevation  \
0       15585.75010   0.276409   0.076935   85.79104         68   
1       15080.14281   0.256626   0.161844  240.09620        828   
4       14795.41238   0.490961   0.363601  173.99826         75   
5       14609.53463   0.396181   0.306116   89.37942         68   
6       14744.06481   0.352804   0.292128  110.89202         40   

   precipitation_sum      slope  landslide_trigger  
0        76083.62956  12.437977                  9  
1        49711.02632   3.715572                  4  
4        47384.80481  11.947599                  4  
5        20904.96219  56.214066                 12  
6        28623.51198  22.222166                 12  

[5 rows x 114 columns]

In [ ]:
df.size

499662

In [ ]:
x = df.iloc[:,1:-1].values
y= df.iloc[:,-1].values

In [ ]:
print(x)

[[7.00000000e+00 2.00000000e+00 0.00000000e+00 ... 6.80000000e+01
  7.60836296e+04 1.24379770e+01]
 [6.00000000e+00 2.00000000e+00 4.00000000e+00 ... 8.28000000e+02
  4.97110263e+04 3.71557240e+00]
 [6.00000000e+00 1.00000000e+00 0.00000000e+00 ... 7.50000000e+01
  4.73848048e+04 1.19475990e+01]
 ...
 [7.00000000e+00 3.00000000e+00 0.00000000e+00 ... 2.35000000e+02
  3.16836293e+04 1.38575620e+01]
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.40000000e+01
  8.18185791e+04 8.16955600e+00]
 [7.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.27000000e+02
  3.59572674e+04 9.35244200e+00]]


In [ ]:
print(y)

[ 9  4  4 ... 12  2  4]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.33,random_state=0)

In [ ]:
print(x_train)

[[6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.36000000e+02
  3.05342236e+04 3.13543850e+01]
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 3.05000000e+02
  8.56788848e+04 1.02771210e+01]
 [6.00000000e+00 1.00000000e+00 7.00000000e+00 ... 9.48000000e+02
  5.24453470e+04 1.58913010e+01]
 ...
 [1.00000000e+00 2.00000000e+00 0.00000000e+00 ... 8.80000000e+01
  3.36492106e+04 1.89168360e+01]
 [7.00000000e+00 2.00000000e+00 0.00000000e+00 ... 2.24000000e+03
  1.45897010e+04 9.37841900e+00]
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.20900000e+03
  6.34248120e+04 1.72082480e+01]]


In [ ]:
print(x_test)

[[6.00000000e+00 3.00000000e+00 0.00000000e+00 ... 7.00000000e+01
  2.74632876e+04 4.41247560e+01]
 [1.00000000e+01 3.00000000e+00 0.00000000e+00 ... 2.35000000e+02
  2.85137055e+04 2.11423470e+01]
 [6.00000000e+00 2.00000000e+00 6.00000000e+00 ... 2.00000000e+00
  1.08521640e+04 2.66325200e+00]
 ...
 [7.00000000e+00 3.00000000e+00 0.00000000e+00 ... 1.16100000e+03
  3.63607530e+04 7.37886050e+00]
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.56900000e+03
  3.87091781e+04 1.14854470e+01]
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.55900000e+03
  8.09123677e+04 3.97238920e+01]]


In [ ]:
print(y_train)

[ 4 12 12 ... 14  4  4]


In [ ]:
print(y_test)

[12 15  4 ...  4 12 14]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-0.25816097 -0.47842176 -0.12862931 ... -0.70894797 -0.56090323
   1.3676867 ]
 [-0.25816097 -0.47842176 -0.12862931 ... -0.46727045  1.51093028
  -0.4626406 ]
 [-0.25816097 -2.27006243  0.54421099 ...  0.45224817  0.26231698
   0.02488885]
 ...
 [-3.49730891 -0.47842176 -0.12862931 ... -0.77759011 -0.44387043
   0.28762311]
 [ 0.38966861 -0.47842176 -0.12862931 ...  2.29986567 -1.159953
  -0.54068293]
 [-0.25816097 -0.47842176 -0.12862931 ...  0.82548978  0.67482516
   0.13925114]]


In [ ]:
print(x_test)

[[-0.25816097  1.31321891 -0.12862931 ... -0.80333091 -0.67628101
   2.47665221]
 [ 2.33315738  1.31321891 -0.12862931 ... -0.56737357 -0.63681588
   0.48088413]
 [-0.25816097 -0.47842176  0.44809095 ... -0.90057394 -1.30037556
  -1.12382092]
 ...
 [ 0.38966861  1.31321891 -0.12862931 ...  0.75684765 -0.34199539
  -0.71432247]
 [-0.25816097 -0.47842176 -0.12862931 ...  1.34030581 -0.25376299
  -0.35771085]
 [-0.25816097 -0.47842176 -0.12862931 ...  1.32600536  1.33184804
   2.09448583]]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 30, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30, random_state=0)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[12 12]
 [12 15]
 [ 4  4]
 ...
 [ 4  4]
 [ 4 12]
 [14 14]]


##Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   3   0   0   0   0   0   0   2   0   0   0]
 [  0  19   0  45   0   0   0   0   0   0  10   0   1   0]
 [  0   0   0   2   0   0   0   0   0   0   0   0   0   0]
 [  0   4   0 662   0   0   0   0   0   0  46   0   5   9]
 [  0   0   0   4   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   2   0   1   0   0   0   0   3   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   2   0   0   2]
 [  0   0   0   8   0   0   0   3   0   0   2   0   0   0]
 [  0   0   0  15   0   0   0   0   5   0   2   0   1   0]
 [  0   0   0   1   0   0   0   0   0   1   0   0   0   1]
 [  0   0   0 208   0   0   0   1   0   1  84   0   2  17]
 [  0   0   0   8   0   0   0   0   0   0   1   0   0   5]
 [  0   0   0  60   0   0   0   0   0   0   5   0  55   0]
 [  0   0   0  77   0   0   0   0   0   0  15   0   2  42]]


0.6026261230131306